insert into storage.buckets (id,
                             name,
                             public,
                             avif_autodetection,
                             file_size_limit,
                             allowed_mime_types,
                             type)
values ('medias',
        'medias',
        false,
        false,
        null,
        array ['image/*', 'video/*'],
        'STANDARD'),
       ('thumbnails',
        'thumbnails',
        false,
        false,
        null,
        array ['image/*'],
        'STANDARD'),
       ('arcana-vault',
        'arcana-vault',
        false,
        false,
        null,
        null,
        'STANDARD'),
       ('resized',
        'resized',
        false,
        false,
        null,
        array ['image/*'],
        'STANDARD')
on conflict (id) do update set name               = excluded.name,
                               public             = excluded.public,
                               avif_autodetection = excluded.avif_autodetection,
                               file_size_limit    = excluded.file_size_limit,
                               allowed_mime_types = excluded.allowed_mime_types,
                               type               = excluded.type;
